// All the words on the site: titles, roll notes, captions, alt texts and the poem.
// Edit freely. Each frame's "id" points to its image in photos.js.
// To remove a frame, delete its { ... } block here (and, if you like, its line in photos.js).
window.SITE = {
  site: {
    title: "I didn’t take these photographs.",
    span: "2019 to 2026",
    subtitle: "Each roll belongs to someone else.",
    intro: [
      "I was looking through my old photographs when this sentence came to me, and it hasn’t left.",
      "They all carry my name. But the people who took them, the ones who knew what they were looking at and why, aren’t here anymore. This page belongs to them. Where I don’t remember, I’ve left it blank.",
    ],
    next: {
      who: "taken by: no one yet",
      note: "The next roll. I won’t have taken these either.",
    },
    letter: {
      title: "I Didn’t Take These Photographs",
      lines: [
        "I didn’t take these photographs",
        "I can’t say the finger that pressed the shutter is mine",
        "Many cells have been born and died since",
        "I cannot see now what I saw through the viewfinder then",
        "The thoughts that led me to shoot back then are no longer in my mind",
        "The feelings that arose are no longer the same",
        "The people who took me to those places are no longer in my contacts",
        "And people who are very dear to me today were strangers then",
        "My likes and dislikes are irrelevant now",
        "I do not even dream the same way",
        "I am neither the same nor a brand new person",
        "These photographs are not mine",
        "The shutter was pressed,",
        "but there was no one pressing it",
      ],
      date: "2026-01-02",
    },
  },
  rolls: [
    {
      year: "2019",
      stock: "Film unknown",
      edge: "135",
      who: "taken by: someone in June 2019",
      note: "They liked railings, stairways, empty paths. In one mirror they caught someone holding a camera. It might have been them.",
      frames: [
        {
          id: "roll01-frame01",
          n: 1,
          w: 1000,
          h: 671,
          alt: "Frame 1, June 2019",
          cap: "",
        },
        {
          id: "roll01-frame02",
          n: 2,
          w: 1000,
          h: 671,
          alt: "Frame 2, June 2019",
          cap: "",
        },
        {
          id: "roll01-frame03",
          n: 3,
          w: 1000,
          h: 671,
          alt: "Pine trees seen from below",
          cap: "",
        },
        {
          id: "roll01-frame04",
          n: 4,
          w: 1000,
          h: 671,
          alt: "Frame 4, June 2019",
          cap: "",
        },
        {
          id: "roll01-frame05",
          n: 5,
          w: 1000,
          h: 671,
          alt: "Frame 5, June 2019",
          cap: "",
        },
        {
          id: "roll01-frame06",
          n: 6,
          w: 1000,
          h: 671,
          alt: "Sunlit stone stairs",
          cap: "",
        },
        {
          id: "roll01-frame07",
          n: 7,
          w: 1000,
          h: 671,
          alt: "A lit sign on a dark wall reading 'Her şey güzel olacak'",
          cap: "Someone put this on a sign. Whoever took the picture must have believed it.",
        },
        {
          id: "roll01-frame08",
          n: 8,
          w: 1000,
          h: 671,
          alt: "Frame 8, June 2019",
          cap: "",
        },
        {
          id: "roll01-frame09",
          n: 9,
          w: 1000,
          h: 671,
          alt: "Frame 9, June 2019",
          cap: "",
        },
        {
          id: "roll01-frame11",
          n: 11,
          w: 1000,
          h: 671,
          alt: "A woman holding a camera in a mirror",
          cap: "Someone in a mirror, holding a camera. Half their face is behind it.",
        },
        {
          id: "roll01-frame12",
          n: 12,
          w: 1000,
          h: 671,
          alt: "Frame 12, June 2019",
          cap: "",
        },
        {
          id: "roll01-frame15",
          n: 15,
          w: 1000,
          h: 671,
          alt: "A dim laundry room",
          cap: "",
        },
      ],
    },
    {
      year: "2019",
      stock: "Film unknown",
      edge: "135",
      who: "taken by: someone in July 2019",
      note: "The roll opens with a neon question mark. A ferry facing the Maiden’s Tower, a gull, a kitten. Towards the end, light got in.",
      frames: [
        {
          id: "roll02-frame01",
          n: 1,
          w: 1000,
          h: 663,
          alt: "A green neon question mark in the dark",
          cap: "The first frame of the roll is a question mark.",
        },
        {
          id: "roll02-frame05",
          n: 5,
          w: 1000,
          h: 663,
          alt: "A narrow, colourful street",
          cap: "",
        },
        {
          id: "roll02-frame06",
          n: 6,
          w: 1000,
          h: 663,
          alt: "Frame 6, July 2019",
          cap: "",
        },
        {
          id: "roll02-frame08",
          n: 8,
          w: 1000,
          h: 663,
          alt: "A gull gliding across a blue sky",
          cap: "",
        },
        {
          id: "roll02-frame11",
          n: 11,
          w: 1000,
          h: 663,
          alt: "The Maiden's Tower with a light leak at the edge",
          cap: "",
        },
        {
          id: "roll02-frame15",
          n: 15,
          w: 1000,
          h: 663,
          alt: "Frame 15, July 2019",
          cap: "",
        },
        {
          id: "roll02-frame16",
          n: 16,
          w: 1000,
          h: 663,
          alt: "Frame 16, July 2019",
          cap: "",
        },
      ],
    },
    {
      year: "2019",
      stock: "Film unknown",
      edge: "135",
      who: "taken by: someone in August 2019",
      note: "Flowers, colors, stones by the sea. In the last frame the sun sets behind wind turbines. Summer must have been ending.",
      frames: [
        {
          id: "roll03-frame01",
          n: 1,
          w: 1000,
          h: 663,
          alt: "Frame 1, August 2019",
          cap: "",
        },
        {
          id: "roll03-frame02",
          n: 2,
          w: 1000,
          h: 663,
          alt: "Iced coffee and purple flowers on a table",
          cap: "",
        },
        {
          id: "roll03-frame05",
          n: 5,
          w: 1000,
          h: 663,
          alt: "Frame 5, August 2019",
          cap: "",
        },
        {
          id: "roll03-frame06",
          n: 6,
          w: 1000,
          h: 663,
          alt: "Frame 6, August 2019",
          cap: "",
        },
        {
          id: "roll03-frame07",
          n: 7,
          w: 1000,
          h: 663,
          alt: "Frame 7, August 2019",
          cap: "",
        },
        {
          id: "roll03-frame12",
          n: 12,
          w: 1000,
          h: 663,
          alt: "Frame 12, August 2019",
          cap: "",
        },
        {
          id: "roll03-frame13",
          n: 13,
          w: 1000,
          h: 663,
          alt: "Two rocks in the sea",
          cap: "",
        },
        {
          id: "roll03-frame18",
          n: 18,
          w: 1000,
          h: 663,
          alt: "Frame 18, August 2019",
          cap: "",
        },
        {
          id: "roll03-frame19",
          n: 19,
          w: 1000,
          h: 663,
          alt: "Frame 19, August 2019",
          cap: "",
        },
        {
          id: "roll03-frame20",
          n: 20,
          w: 1000,
          h: 663,
          alt: "A hen, up close",
          cap: "",
        },
        {
          id: "roll03-frame23",
          n: 23,
          w: 1000,
          h: 663,
          alt: "Wind turbines at sunset",
          cap: "Possibly the last frame of that summer.",
        },
      ],
    },
    {
      year: "2021",
      stock: "Film unknown",
      edge: "135",
      who: "taken by: someone two years later, in June 2021",
      note: "Cherries, strawberries, a table full of food. A cat asleep under a shelf. A ferry leaving a trail of foam behind it.",
      frames: [
        {
          id: "roll04-frame02",
          n: 2,
          w: 1000,
          h: 675,
          alt: "A white and tabby cat lying on a bed",
          cap: "",
        },
        {
          id: "roll04-frame05",
          n: 5,
          w: 1000,
          h: 675,
          alt: "A table set for dinner",
          cap: "",
        },
        {
          id: "roll04-frame08",
          n: 8,
          w: 1000,
          h: 675,
          alt: "Frame 8, June 2021",
          cap: "",
        },
        {
          id: "roll04-frame10",
          n: 10,
          w: 1000,
          h: 675,
          alt: "Frame 10, June 2021",
          cap: "",
        },
        {
          id: "roll04-frame14",
          n: 14,
          w: 1000,
          h: 675,
          alt: "Frame 14, June 2021",
          cap: "",
        },
        {
          id: "roll04-frame17",
          n: 17,
          w: 1000,
          h: 675,
          alt: "Frame 17, June 2021",
          cap: "",
        },
        {
          id: "roll04-frame18",
          n: 18,
          w: 1000,
          h: 675,
          alt: "A tabby cat crouching on the ground",
          cap: "",
        },
        {
          id: "roll04-frame19",
          n: 19,
          w: 1000,
          h: 675,
          alt: "Frame 19, June 2021",
          cap: "",
        },
      ],
    },
    {
      year: "2021",
      stock: "Lomo, film unknown",
      edge: "LOMO 135",
      who: "taken by: someone that same month, with a different camera",
      note: "Most of this roll is gone. The frames got too much light or none at all. What’s left: a candle, a sofa, someone behind the wheel.",
      frames: [
        {
          id: "roll05-frame01",
          n: 1,
          w: 1000,
          h: 675,
          alt: "A red-lit scene against a sunset",
          cap: "",
        },
        {
          id: "roll05-frame02",
          n: 2,
          w: 1000,
          h: 675,
          alt: "Frame 2, June 2021",
          cap: "",
        },
        {
          id: "roll05-frame03",
          n: 3,
          w: 1000,
          h: 675,
          alt: "Frame 3, June 2021",
          cap: "",
        },
        {
          id: "roll05-frame04",
          n: 4,
          w: 1000,
          h: 675,
          alt: "Frame 4, June 2021",
          cap: "",
        },
        {
          id: "roll05-frame30",
          n: 30,
          w: 1000,
          h: 675,
          alt: "Slugs on a stone",
          cap: "",
        },
        {
          id: "roll05-frame33",
          n: 33,
          w: 1000,
          h: 675,
          alt: "Someone at a table under red light",
          cap: "",
        },
        {
          id: "roll05-frame34",
          n: 34,
          w: 1000,
          h: 675,
          alt: "Frame 34, June 2021",
          cap: "",
        },
      ],
    },
    {
      year: "2021",
      stock: "Diana, film unknown",
      edge: "DIANA 135",
      who: "taken by: someone in July 2021 who fit two moments into every frame",
      note: "The sea, boats, cats at a window. At the end of the roll, a ferry heading back to Istanbul.",
      frames: [
        {
          id: "roll06-frame04",
          n: 4,
          w: 1000,
          h: 675,
          alt: "Frame 4, July 2021",
          cap: "",
        },
        {
          id: "roll06-frame05",
          n: 5,
          w: 1000,
          h: 675,
          alt: "Half frames: boats in a bay",
          cap: "",
        },
        {
          id: "roll06-frame08",
          n: 8,
          w: 1000,
          h: 675,
          alt: "Frame 8, July 2021",
          cap: "",
        },
        {
          id: "roll06-frame09",
          n: 9,
          w: 1000,
          h: 675,
          alt: "Frame 9, July 2021",
          cap: "",
        },
        {
          id: "roll06-frame14",
          n: 14,
          w: 1000,
          h: 675,
          alt: "Half frames: engine parts against a wall, and someone lying under a car",
          cap: "",
        },
        {
          id: "roll06-frame16",
          n: 16,
          w: 1000,
          h: 675,
          alt: "Cats looking through a window",
          cap: "",
        },
        {
          id: "roll06-frame17",
          n: 17,
          w: 1000,
          h: 675,
          alt: "A ferry's hull with lifebuoys",
          cap: "",
        },
        {
          id: "roll06-frame18",
          n: 18,
          w: 1000,
          h: 675,
          alt: "Frame 18, July 2021",
          cap: "",
        },
        {
          id: "roll06-frame19",
          n: 19,
          w: 1000,
          h: 675,
          alt: "Frame 19, July 2021",
          cap: "",
        },
        {
          id: "roll06-frame20",
          n: 20,
          w: 1000,
          h: 675,
          alt: "Harbour cranes and the sea",
          cap: "",
        },
        {
          id: "roll06-frame21",
          n: 21,
          w: 1000,
          h: 675,
          alt: "Frame 21, July 2021",
          cap: "",
        },
        {
          id: "roll06-frame24",
          n: 24,
          w: 1000,
          h: 675,
          alt: "Frame 24, July 2021",
          cap: "",
        },
        {
          id: "roll06-frame26",
          n: 26,
          w: 1000,
          h: 675,
          alt: "Galata Tower in the distance across the water",
          cap: "",
        },
      ],
    },
    {
      year: "2021",
      stock: "Black and white, film unknown",
      edge: "B&W 135",
      who: "taken by: someone that same summer who gave up on colour",
      note: "A black cat beside a flowerpot, a dog asleep in the shade. In one frame, someone turned their camera back on them.",
      frames: [
        {
          id: "roll07-frame01",
          n: 1,
          w: 1000,
          h: 675,
          alt: "Frame 1, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame02",
          n: 2,
          w: 1000,
          h: 675,
          alt: "Frame 2, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame03",
          n: 3,
          w: 1000,
          h: 675,
          alt: "Frame 3, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame04",
          n: 4,
          w: 1000,
          h: 675,
          alt: "Frame 4, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame05",
          n: 5,
          w: 1000,
          h: 675,
          alt: "Frame 5, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame06",
          n: 6,
          w: 1000,
          h: 675,
          alt: "Black and white: a black cat beside a flowerpot",
          cap: "",
        },
        {
          id: "roll07-frame07",
          n: 7,
          w: 1000,
          h: 675,
          alt: "Frame 7, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame08",
          n: 8,
          w: 1000,
          h: 675,
          alt: "Black and white: people on a staircase",
          cap: "",
        },
        {
          id: "roll07-frame09",
          n: 9,
          w: 1000,
          h: 675,
          alt: "Black and white: someone looking in from a doorway",
          cap: "",
        },
        {
          id: "roll07-frame12",
          n: 12,
          w: 1000,
          h: 675,
          alt: "Frame 12, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame13",
          n: 13,
          w: 1000,
          h: 675,
          alt: "Black and white: an old building's facade",
          cap: "",
        },
        {
          id: "roll07-frame15",
          n: 15,
          w: 1000,
          h: 675,
          alt: "Black and white: boats in a harbour",
          cap: "",
        },
        {
          id: "roll07-frame16",
          n: 16,
          w: 1000,
          h: 675,
          alt: "Frame 16, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame17",
          n: 17,
          w: 1000,
          h: 675,
          alt: "Frame 17, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame18",
          n: 18,
          w: 1000,
          h: 675,
          alt: "Black and white: a shaggy dog asleep on the floor",
          cap: "",
        },
        {
          id: "roll07-frame19",
          n: 19,
          w: 1000,
          h: 675,
          alt: "Frame 19, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame20",
          n: 20,
          w: 1000,
          h: 675,
          alt: "Black and white: someone pointing a camera back",
          cap: "Another camera. This time on the other side.",
        },
        {
          id: "roll07-frame21",
          n: 21,
          w: 1000,
          h: 675,
          alt: "Frame 21, summer 2021",
          cap: "",
        },
        {
          id: "roll07-frame22",
          n: 22,
          w: 1000,
          h: 675,
          alt: "Black and white: a bare tree in fog",
          cap: "",
        },
        {
          id: "roll07-frame24",
          n: 24,
          w: 1000,
          h: 675,
          alt: "Black and white: a dog asleep under a table",
          cap: "",
        },
        {
          id: "roll07-frame25",
          n: 25,
          w: 1000,
          h: 675,
          alt: "Frame 25, summer 2021",
          cap: "",
        },
      ],
    },
    {
      year: "2021",
      stock: "Lomography Lomochrome Metropolis 100–400",
      edge: "METROPOLIS 100-400",
      who: "taken by: someone in 2021 who didn’t write down when",
      note: "Stone ruins among trees, two kayaks at the water’s edge, a crowded bridge. I can’t tell whether the colours were already this pale.",
      frames: [
        {
          id: "roll08-frame01",
          n: 1,
          w: 663,
          h: 1000,
          alt: "Frame 1, 2021",
          cap: "",
        },
        {
          id: "roll08-frame02",
          n: 2,
          w: 1000,
          h: 663,
          alt: "Frame 2, 2021",
          cap: "",
        },
        {
          id: "roll08-frame03",
          n: 3,
          w: 1000,
          h: 663,
          alt: "A vaulted ceiling",
          cap: "",
        },
        {
          id: "roll08-frame04",
          n: 4,
          w: 1000,
          h: 663,
          alt: "Trees on a lakeshore",
          cap: "",
        },
        {
          id: "roll08-frame05",
          n: 5,
          w: 1000,
          h: 663,
          alt: "Frame 5, 2021",
          cap: "",
        },
        {
          id: "roll08-frame06",
          n: 6,
          w: 1000,
          h: 663,
          alt: "Frame 6, 2021",
          cap: "",
        },
        {
          id: "roll08-frame07",
          n: 7,
          w: 1000,
          h: 663,
          alt: "Frame 7, 2021",
          cap: "",
        },
        {
          id: "roll08-frame08",
          n: 8,
          w: 1000,
          h: 663,
          alt: "Stone ruins between pine trees",
          cap: "",
        },
        {
          id: "roll08-frame09",
          n: 9,
          w: 1000,
          h: 663,
          alt: "Frame 9, 2021",
          cap: "",
        },
        {
          id: "roll08-frame10",
          n: 10,
          w: 1000,
          h: 663,
          alt: "Frame 10, 2021",
          cap: "",
        },
        {
          id: "roll08-frame11",
          n: 11,
          w: 1000,
          h: 663,
          alt: "Frame 11, 2021",
          cap: "",
        },
        {
          id: "roll08-frame12",
          n: 12,
          w: 1000,
          h: 663,
          alt: "Two people walking through tall grass",
          cap: "",
        },
        {
          id: "roll08-frame13",
          n: 13,
          w: 1000,
          h: 663,
          alt: "A stone sarcophagus with holes in it",
          cap: "",
        },
        {
          id: "roll08-frame14",
          n: 14,
          w: 1000,
          h: 663,
          alt: "A red and a yellow kayak at the water's edge",
          cap: "",
        },
        {
          id: "roll08-frame17",
          n: 17,
          w: 1000,
          h: 663,
          alt: "Frame 17, 2021",
          cap: "",
        },
        {
          id: "roll08-frame18",
          n: 18,
          w: 1000,
          h: 663,
          alt: "A dog stretched out on a sofa",
          cap: "",
        },
        {
          id: "roll08-frame19",
          n: 19,
          w: 663,
          h: 1000,
          alt: "Frame 19, 2021",
          cap: "",
        },
        {
          id: "roll08-frame20",
          n: 20,
          w: 1000,
          h: 663,
          alt: "Frame 20, 2021",
          cap: "",
        },
        {
          id: "roll08-frame21",
          n: 21,
          w: 1000,
          h: 663,
          alt: "Frame 21, 2021",
          cap: "",
        },
        {
          id: "roll08-frame22",
          n: 22,
          w: 1000,
          h: 663,
          alt: "Frame 22, 2021",
          cap: "",
        },
        {
          id: "roll08-frame23",
          n: 23,
          w: 1000,
          h: 663,
          alt: "Someone grilling fish on a bridge",
          cap: "",
        },
        {
          id: "roll08-frame24",
          n: 24,
          w: 1000,
          h: 663,
          alt: "Frame 24, 2021",
          cap: "",
        },
        {
          id: "roll08-frame25",
          n: 25,
          w: 1000,
          h: 663,
          alt: "A ferry on the water",
          cap: "",
        },
        {
          id: "roll08-frame26",
          n: 26,
          w: 1000,
          h: 663,
          alt: "Frame 26, 2021",
          cap: "",
        },
        {
          id: "roll08-frame27",
          n: 27,
          w: 1000,
          h: 663,
          alt: "Frame 27, 2021",
          cap: "",
        },
        {
          id: "roll08-frame28",
          n: 28,
          w: 1000,
          h: 663,
          alt: "Frame 28, 2021",
          cap: "",
        },
      ],
    },
    {
      year: "2025",
      stock: "Lomography Potsdam 100",
      edge: "POTSDAM 100",
      who: "taken by: someone four years later, in 2025",
      note: "Almost nothing is in focus. A room, a man, a baby laughing on the floor. Maybe that was enough. There was a little knowledge on focus and light",
      frames: [
        {
          id: "roll09-frame02",
          n: 2,
          w: 1000,
          h: 663,
          alt: "Frame 2, 2025",
          cap: "",
        },
        {
          id: "roll09-frame03",
          n: 3,
          w: 1000,
          h: 663,
          alt: "Frame 3, 2025",
          cap: "",
        },
        {
          id: "roll09-frame04",
          n: 4,
          w: 663,
          h: 1000,
          alt: "A blurred, seated man",
          cap: "",
        },
        {
          id: "roll09-frame05",
          n: 5,
          w: 663,
          h: 1000,
          alt: "A ghostly, faint silhouette",
          cap: "",
        },
        {
          id: "roll09-frame06",
          n: 6,
          w: 663,
          h: 1000,
          alt: "A blurred man in motion",
          cap: "",
        },
        {
          id: "roll09-frame07",
          n: 7,
          w: 663,
          h: 1000,
          alt: "Frame 7, 2025",
          cap: "",
        },
        {
          id: "roll09-frame08",
          n: 8,
          w: 1000,
          h: 663,
          alt: "A baby sitting on the floor, laughing",
          cap: "Nothing is sharp, but the baby is laughing.",
        },
        {
          id: "roll09-frame09",
          n: 9,
          w: 1000,
          h: 663,
          alt: "A blurred baby crawling",
          cap: "",
        },
        {
          id: "roll09-frame13",
          n: 13,
          w: 663,
          h: 1000,
          alt: "A faint, blurred room",
          cap: "",
        },
      ],
      gapBefore: {
        years: ["2022", "2023", "2024"],
        text: "No rolls from these years. Either nothing was taken, or something is still sitting somewhere, waiting to be developed.",
      },
    },
    {
      year: "2026",
      stock: "Kodak UltraMax 400",
      edge: "KODAK UMAX 400",
      who: "taken by: someone in 2026",
      note: "Fog, a church tower, old houses, a pushchair. A hand reaching down towards someone small.",
      frames: [
        {
          id: "roll10-frame01",
          n: 1,
          w: 1000,
          h: 663,
          alt: "A lake in fog",
          cap: "",
        },
        {
          id: "roll10-frame02",
          n: 2,
          w: 1000,
          h: 663,
          alt: "An almost completely dark frame",
          cap: "Left in the dark.",
        },
        {
          id: "roll10-frame03",
          n: 3,
          w: 1000,
          h: 663,
          alt: "Frame 3, 2026",
          cap: "",
        },
        {
          id: "roll10-frame04",
          n: 4,
          w: 1000,
          h: 663,
          alt: "A blurred, laughing baby",
          cap: "",
        },
        {
          id: "roll10-frame05",
          n: 5,
          w: 1000,
          h: 663,
          alt: "A baby in a high chair in a kitchen",
          cap: "",
        },
        {
          id: "roll10-frame06",
          n: 6,
          w: 1000,
          h: 663,
          alt: "Frame 6, 2026",
          cap: "",
        },
        {
          id: "roll10-frame07",
          n: 7,
          w: 1000,
          h: 663,
          alt: "A child in a pink coat being carried, and a man in glasses",
          cap: "",
        },
        {
          id: "roll10-frame08",
          n: 8,
          w: 1000,
          h: 663,
          alt: "A child in a pink coat, from behind",
          cap: "",
        },
        {
          id: "roll10-frame09",
          n: 9,
          w: 1000,
          h: 663,
          alt: "Frame 9, 2026",
          cap: "",
        },
        {
          id: "roll10-frame10",
          n: 10,
          w: 1000,
          h: 663,
          alt: "Frame 10, 2026",
          cap: "",
        },
        {
          id: "roll10-frame11",
          n: 11,
          w: 1000,
          h: 663,
          alt: "Frame 11, 2026",
          cap: "",
        },
        {
          id: "roll10-frame12",
          n: 12,
          w: 1000,
          h: 663,
          alt: "Someone pushing a pram past old houses",
          cap: "",
        },
        {
          id: "roll10-frame13",
          n: 13,
          w: 1000,
          h: 663,
          alt: "Frame 13, 2026",
          cap: "",
        },
        {
          id: "roll10-frame14",
          n: 14,
          w: 1000,
          h: 663,
          alt: "A church tower in fog",
          cap: "",
        },
        {
          id: "roll10-frame15",
          n: 15,
          w: 1000,
          h: 663,
          alt: "A bare tree by the water",
          cap: "",
        },
        {
          id: "roll10-frame16",
          n: 16,
          w: 1000,
          h: 663,
          alt: "A hand reaching down towards a baby",
          cap: "Someone looking up. The hand reaching down must belong to whoever took this.",
        },
        {
          id: "roll10-frame17",
          n: 17,
          w: 1000,
          h: 663,
          alt: "Frame 17, 2026",
          cap: "",
        },
        {
          id: "roll10-frame18",
          n: 18,
          w: 1000,
          h: 663,
          alt: "A baby looking into the camera",
          cap: "",
        },
        {
          id: "roll10-frame19",
          n: 19,
          w: 1000,
          h: 663,
          alt: "A man in glasses, laughing",
          cap: "The last frame of the roll.",
        },
      ],
    },
  ],
};
